repos:
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
    -   id: uv-lock
    -   id: uv-export

-   repo: local
    hooks:
    -   id: ruff
        name: Run ruff check only
        entry: uvx ruff check .
        language: python
        types: [python]

-  repo: local
   hooks:
   -  id: bandit
      name: do a bandit check on the project files only not all
      entry: bandit -r .\WebApp.py
      language: python
      types: [python]