name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bandit Check
        run: bandit -r -b baseline.json .

  ruff:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff Check
        run: ruff check ./WebApp.py
